name: Test Notifications

on:
  workflow_run:
    workflows: ["Test & Quality Assurance", "Code Coverage"]
    types:
      - completed

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  notify-failure:
    name: Notify on Test Failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Get PR number
        id: pr
        uses: actions/github-script@v8
        with:
          script: |
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.payload.workflow_run.head_branch}`
            });
            
            if (pulls.data.length > 0) {
              return pulls.data[0].number;
            }
            return null;
      
      - name: Comment on PR
        if: steps.pr.outputs.result != 'null'
        uses: actions/github-script@v8
        with:
          script: |
            const prNumber = ${{ steps.pr.outputs.result }};
            const workflowName = '${{ github.event.workflow_run.name }}';
            const runUrl = '${{ github.event.workflow_run.html_url }}';
            
            const comment = `## ⚠️ Test Failure Alert
            
            The **${workflowName}** workflow has failed.
            
            **Details:**
            - Branch: \`${{ github.event.workflow_run.head_branch }}\`
            - Commit: \`${{ github.event.workflow_run.head_sha }}\`
            - Run: [View workflow run](${runUrl})
            
            Please review the failed tests and fix the issues before merging.
            
            ---
            *This is an automated notification from the test failure monitoring system.*`;
            
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  notify-success:
    name: Update Status on Success
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Create success summary
        run: |
          echo "✅ All tests passed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Workflow:** ${{ github.event.workflow_run.name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.event.workflow_run.head_sha }}" >> $GITHUB_STEP_SUMMARY
